# Generated by Django 5.1.3 on 2024-11-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_lineitem_dog_alter_invoice_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
