# Generated by Django 5.1.3 on 2024-11-09 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='dog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.dog'),
        ),
    ]
