# Generated by Django 5.1.3 on 2024-11-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_lineitem_quantity_alter_lineitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='service',
            field=models.CharField(choices=[('Group Walk', 'Group Walk'), ('Pet Visit', 'Pet Visit')], max_length=100),
        ),
    ]
