# Generated by Django 5.1.3 on 2024-11-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_remove_client_address_client_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='service',
            field=models.CharField(choices=[('Group Walk', 'Group Walk'), ('Pet Visit', 'Pet Visit'), ('Dog Sitting', 'Dog Sitting')], max_length=100),
        ),
    ]
