# Generated by Django 5.1.3 on 2024-11-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_lineitem_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='custom_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='service',
            field=models.CharField(blank=True, choices=[('Group Walk', 'Group Walk'), ('Pet Visit', 'Pet Visit'), ('Dog Sitting', 'Dog Sitting')], max_length=100, null=True),
        ),
    ]
