# Generated by Django 5.1.3 on 2024-11-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_client_current_invoice_number_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('client', 'invoice_number')},
        ),
    ]
