# Generated by Django 5.1.3 on 2024-11-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='custom_service',
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
