# Generated by Django 5.1.3 on 2024-11-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_remove_lineitem_custom_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
