# Generated by Django 5.1.3 on 2024-11-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_alter_lineitem_unit_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='service',
            field=models.CharField(choices=[('Group Walk', 'Group Walk'), ('Pet Visit', 'Pet Visit'), ('Dog Sitting', 'Dog Sitting')], default='Group Walk', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('client', 'invoice_number'), name='unique_invoice_per_client'),
        ),
    ]
