# Generated by Django 5.1.3 on 2024-11-25 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_alter_invoice_unique_together_alter_lineitem_service_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_per_client',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.client'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('client', 'invoice_number')},
        ),
    ]
