# Generated by Django 5.1.3 on 2025-01-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_remove_invoice_unique_invoice_per_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='weekly_walks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
