# Generated by Django 5.1.3 on 2025-01-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_dog_weekly_walks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='service',
            field=models.CharField(choices=[('Group Walk', 'Group Walk'), ('Pet Visit', 'Pet Visit'), ('Dog Sitting', 'Dog Sitting'), ('Late Cancellation', 'Late Cancellation')], max_length=100),
        ),
    ]
